const products = [
  {
    id: 1,
    name: "Burgurs",
    imgUrl: "images/g-1.jpg",
    price: 150,
    stock: 100,
    discription: "Portobello Mushroom Burgers.",
  },
  {
    id: 2,
    name: "Sandwiches",
    imgUrl: "images/g-2.jpg",
    price: 190,
    stock: 100,
    discription: "Roast Beef Sandwich.",
  },
  {
    id: 3,
    name: "Frankies & rolls",
    imgUrl: "images/g-3.jpg",
    price: 200,
    stock: 100,
    discription: "Paneer Frankie.",
  },
  {
    id: 4,
    name: "cupcakes",
    imgUrl: "images/g-4.jpg",
    price: 200,
    stock: 100,
    discription: "Coconut Cupcakes.",
  },
  {
    id: 5,
    name: "Sweets",
    imgUrl: "images/g-5.jpg",
    price: 250,
    stock: 100,
    discription: "Shrikhand.",
  },
  {
    id: 6,
    name: "Pakodas",
    imgUrl: "images/g-6.jpg",
    price: 300,
    stock: 100,
    discription: "Thika Pakodas.",
  },
  {
    id: 7,
    name: "Breakfast",
    imgUrl: "images/g-7.jpg",
    price: 340,
    stock: 100,
    discription: "Coconut Cupcakes.",
  },
  {
    id: 8,
    name: "chocolate",
    imgUrl: "images/g-8.jpg",
    price: 120,
    stock: 100,
    discription: "Dark Chocolate"
  },
];

